### ISSUE TITLE
Error trying test datasets

### ISSUE THREAD

**Issue by drperpen** [IngmarLudwig/HalfedgeCNN#1]
Hi,
I am trying to run the training with:
```
bash scripts/get_shrec_data.sh
python scripts/train_with_settings.py shrec_16
```

But I am getting this error:
``` 
 File "/mnt/E/dev/pytorch_geom/venv/lib/python3.11/site-packages/numpy/lib/npyio.py", line 740, in _savez
    val = np.asanyarray(val)
          ^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (252,) + inhomogeneous part.
```

Is there any python/pytorch/numpy version conflict I should be aware of? I also tried with the segmentation dataset and got the same error (with a different shape value)
Thanks!

**Comment by IngmarLudwig** [comment]
Hi drperpen,

indeed, the new version of np.savez_compressed did not accept my inhomogeneous list as an input. 

I added a workaround to the code. On my system it is working again.

Does it work on your system now?

Best regards,
Ingmar Ludwig

**Comment by drperpen** [comment]
Thank you for you reply and your solution, Ingmar. After also changing this:
https://github.com/IngmarLudwig/HalfedgeCNN/blob/a958b67dcd026f6a5cfa027c6f146b3f60ee293d/models/layers/half_edge_mesh_pool.py#L27

to: `np.bool_`

everything worked as expected.

**Comment by IngmarLudwig** [comment]
Good to hear and thank you for the information!

**Comment by IngmarLudwig** [comment]
Good to hear and thank you for the information!
